name: bus_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  drift: ^2.34.4
  flutter_map: ^8.3.0
  flutter_map_vector_tiles: ^2.7.0
  latlong2: ^0.10.1
  gpx: ^2.3.0
  http: ^1.6.0
  geolocator: ^14.0.3
  shared_preferences: ^2.3.2
  web_socket_channel: ^3.0.3
  flutter_dotenv: ^6.0.1
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_animate: ^4.5.2
  permission_handler: ^13.0.1
  path: ^1.9.0
  connectivity_plus: ^7.0.0
  path_provider: ^2.1.5

dev_dependencies:
  drift_dev: ^2.34.6
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/fonts/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Variable.ttf
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Variable.ttf
